#Snakefile

import pandas as pd 
from snakemake.utils import min_version

min_version("9.0")

configfile: "config/config.yaml"

LIBRARY_BATCHES, = glob_wildcards("data/{library_batch}.matrix.mtx.gz")
#global_wildcards: mira que archivos existen en mi data y extrae los valores que encajan con el wildcard
# ","-> desempacking, para que quede como lista y no como tupla

wildcard_constraints:
    library_batch=r"[A-Za-z0-9_\-]+",
#una secuencia de uno o más caracteres, donde cada uno es letra, número, guion bajo o guion medio — nada más

#solo es mi regla all, meta: tener un rds por specimenID
# rule all:
#     input:
#         expand(
#             "results/specimens_by_batch/{library_batch}",
#             library_batch=LIBRARY_BATCHES,
#         )


rule all:
    input:
        expand(
            "results/qc_filtered/{library_batch}",
            library_batch=LIBRARY_BATCHES,
        )

#La regla principal que hace el demultiplexing , toma cada archivo de ibreria y usando el scriot de 
#R hace el demultiplexing y genera un rds por specimenID

rule demultiplex_batch:
    input:
        matrix="data/{library_batch}.matrix.mtx.gz",
        barcodes="data/{library_batch}.barcodes.tsv.gz",
        features="data/{library_batch}.features.tsv.gz",
        mapping=config["mapping_csv"], 
    output:
        directory("results/specimens_by_batch/{library_batch}"),
    log:
        "logs/demultiplex_batch/{library_batch}.log"
    threads: 2
    conda:
        "envs/seurat_demultiplexing.yaml"
    script:
        "scripts/demultiplex_batch.R"

#Regla que hace el QC de los rds generados por la regla anterior, toma cada rds y usando el script de R hace el QC y genera un rds por specimenID

rule qc_batch:
    input: #cada uno de las carpetas de cada batch
        specimens_dir="results/specimens_by_batch/{library_batch}",
    output: # dos outputs 
        qc_dir=directory("results/qc_filtered/{library_batch}"), # directorio para guardar los archivos rds filtrados
        summary="results/qc_reports/{library_batch}_qc_summary.csv", # archivo csv para guardar el resumen de QC
    log:
        "logs/qc_batch/{library_batch}.log",
    threads: 2
    conda:
        "envs/seurat_demultiplexing.yaml"
    script:
        "scripts/qc_filter.R"